r=int(input("enter radius "))
b=int(input("enter base "))
h=int(input("enter height "))
s=int(input("enter side "))
l=int(input("enter length "))
br=int(input("enter breath "))
pi=3.14

print("area of circle ",pi*r**2)
print("perimeter of circle ",2*pi*r)
print("area of triangle ",1/2*b*h)
print("perimeter of triangle ",3*s)
print("area of square ",s*s)
print("perimeter of square ",4*s)
print("area of rectangle ",l*br)
print("perimeter of rectangle ",2*(l+br))
